In [1]:
import torch
from torch import nn

class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(self, x):
        return self.corr2d(x, self.weight) + self.bias

    def corr2d(self, X, K):  #@save
        """计算二维互相关运算"""
        h, w = K.shape
        Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
        for i in range(Y.shape[0]):
            for j in range(Y.shape[1]):
                Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
        return Y

In [2]:
conv = Conv2D((4, 4))
conv.weight, conv.bias

(Parameter containing:
 tensor([[-0.3951, -1.4532, -0.2188,  0.7921],
         [ 1.2442,  0.6144,  0.8063,  0.3962],
         [ 0.5998,  0.3292,  0.4099, -1.8171],
         [ 0.6626, -0.3883, -0.2411,  1.0475]], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True))

In [3]:
x1 = torch.randn((16, 16))

In [4]:
x2 = conv.forward(x1)
x3 = conv.forward(x2)
x4 = conv.forward(x3)

In [5]:
x4.shape

torch.Size([7, 7])

In [6]:
torch.rand((3, 3)) + torch.ones(1)

tensor([[1.6959, 1.7846, 1.4224],
        [1.9546, 1.4534, 1.1506],
        [1.8617, 1.9542, 1.8949]])