In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
X = torch.arange(16, dtype=d2l.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [11]:
pool2d = nn.MaxPool2d(2, padding=1, stride=2)
pool2d(X)

tensor([[[[ 0.,  2.,  3.],
          [ 8., 10., 11.],
          [12., 14., 15.]]]])

In [13]:
X = torch.cat((X, X + 1), 1)
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]]]])